### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by martopak** [fajarwz/blog-laravel10-crud-image#1]
![image](https://github.com/fajarwz/blog-laravel10-crud-image/assets/142328815/a298659c-34d5-425d-8154-d1f94903b5ac)
![image](https://github.com/fajarwz/blog-laravel10-crud-image/assets/142328815/0f37e837-dcb7-46f6-8eda-051eedf83eb2)
![image](https://github.com/fajarwz/blog-laravel10-crud-image/assets/142328815/43e5d389-065e-4e01-9c78-f1591905d9ff)

Begini puh, sudah install ulang node, sama bersihin npm cache hasil masih stuck

**Comment by fajarwz** [comment]
udah run `npm install` belum?

kalau udah baru run `npm run dev`

**Comment by martopak** [comment]
> udah run `npm install` belum?
> 
> kalau udah baru run `npm run dev`

Sudah puh,

**Comment by fajarwz** [comment]
3 gambar itu sebenernya 2 error yg berbeda. Untuk gambar pertama itu solusinya, pastikan npm install nya berhasil, ngga ada error. Atau hapus dulu folder node_modules nya baru npm install lalu npm run dev lagi. Kalau masih error coba restart komputer nya.Error gambar 2 dan 3 itu pastikan komponen textarea-input nya ada. Coba kasih bukti ss atau kode kalau komponen itu udah ada dan gimana cara manggilnya di form. Atau sekalian share link reponya kesini

**Comment by martopak** [comment]
https://ungu.in/bukuinduk

**Comment by martopak** [comment]
ungu.in/inipuh ini puh

**Comment by fajarwz** [comment]
ini aku coba clone dan run repo ini bisa sih. php 8.1.10, node v18.15.0

![image](https://github.com/fajarwz/blog-laravel10-crud-image/assets/39845286/a6b0f174-73dd-4cd9-b9e8-ad8b15e274d3)

![image](https://github.com/fajarwz/blog-laravel10-crud-image/assets/39845286/5b2983e6-4b31-4b33-993d-b1aa3aec02dc)

mungkin itu issue dari komputernya, misal ada masalah cache atau apa yg ngga terjangkau oleh repo ini. bisa coba instal laravel kosongan dulu, udah gitu langsung run, cek ada masalah ngga. kalau ga ada baru bertahap ikuti tutorial di yt untuk repo ini

**Comment by fajarwz** [comment]
> > udah run `npm install` belum?
> > kalau udah baru run `npm run dev`
> 
> Sudah puh,

ini memang keliatannya udah betul, coba ikut saran di atas aja ya
